### PR TITLE
1.8.8 port

### PR DESCRIPTION
**Pull request by primetoxinz**
Mostly was just remapping, so I decided I'd take a shot at it. But the worldrenderer changed a lot, check out RenderUtils. I tried to get the sky and clouds working, but I think the texture wasn't binding... or something

### CODE REVIEW

**Comment by tyronx** [comment]
Just a quick summary: You seem to have made a few mistakes and use a different indentation on your editor or something. Also not sure how to handle this change - it's not downards compatible with MC 1.8 is it? 

In any case thank you for your efforts!

**Comment by primetoxinz** [comment]
the worlds should be completely compatible, yes

**Comment by tyronx** [comment]
Worlds yes, but you probably cannot use a VC 1.8.8 built Mod with Minecraft 1.8, can you?

**Comment by primetoxinz** [comment]
but if you want, I suggest making a 1.8.8 branch on your end and I will rePR to that branch instead

no, the mod will not work across versions

**Comment by primetoxinz** [comment]
closing to PR to the other branch

**Pull request closed without merging**
