### PR TITLE
Improved the grind stone sound

### PR DESCRIPTION
**Pull request by nanakisan**
Used parts of this file
http://www.freesound.org/people/j1987/sounds/95007/

to make a cleaner less ear raping grinding sound. sounds much more
natural now

### CODE REVIEW

**Comment by tyronx** [comment]
I'm not quite convinced, but my wife really likes it so pulled, thanks :D

**Comment by tyronx** [comment]
The thing i was kinda missing is the humming sounds of the stones caused by the vibration. This one is only the sounds created from the friction.

**Comment by nanakisan** [comment]
I didn't want to post another PR but I think I nailed a better version of the sound.
https://dropfile.to/DBPPA

I added a bit of low subtle harmonics. It might simulate the hum you hear from the vibration in a 3 meter sized room.

**Comment by tyronx** [comment]
Ok thanks I added it to my local repos I will push to github this evening.

**Comment by nanakisan** [comment]
no problem my good man glad I could be of help

**Pull request merged**
