### PR TITLE
Create zh_CN.lang

### PR DESCRIPTION
**Pull request by mymagadsl**

### CODE REVIEW

**Comment by 3TUSK** [comment]
Hey there, I am 3TUSK, a minecraft mod localizer, and I speak Chinese as first language (to be specific, the simplified one). Not sure if you are pretty familiar with simplified Chinese, but I notice that you seem to translate "redstone" as "雷石东". I don't want to be offensive, but that is probably from machine translation and the correct one is "红石". 
Also I notice several minor wrong translations in your `zh_CN.lang` file. If you don't mind I can help you to correct them. 
I hope you can reply me asap. Thanks for your time.

**Comment by mymagadsl** [comment]
Because you know Chinese, so I used to answer more able to reach the Chinese meaning

這個 zh_CN.lang 的原作者是 zhenadao,

我只是代為上傳,關於翻譯的的錯誤,我的沒有發現到,當然可以的話,希望大家都能一起解決這些問題。讓這個模組能更加本地化.

非常感謝你的協助,我們都不介意.
Thanks to your help, we do not mind.

**Comment by tyronx** [comment]
Please let me know once it's ready,

**Comment by 3TUSK** [comment]
@mymagadsl I have sent [a pull request](https://github.com/mymagadsl/vintagecraft/pull/1) to you, please double check it.

**Comment by mymagadsl** [comment]
3TUSK thank you!
zh_CN.lang ready.

**Comment by 3TUSK** [comment]
@mymagadsl I believe it is good to go and merge this pull request. What do you think?

**Comment by mymagadsl** [comment]
Hello 3TUSK

很抱歉我的英文文法不太好,不太了解你这句话的意思.

另外我已经点击合并了,是不是这样就可以了?

Github 的操作我不太熟悉,只知道Pull requests 可以把语言档提供给作者..

所以我提供很多语言档提供给作者的时候都没有评论

如果有什么不对的地方还请多指教!

Very thank you!

**Comment by 3TUSK** [comment]
@mymagadsl 啊，抱歉我好像没有解释清楚，当时我误以为你还没有合并，所以就回复了一句来问一下你的意见。实际上你可以看到我的提交已经合并到这里来了。
所以说现在已经可以全部提交了，thanks for your understanding！

**Comment by 3TUSK** [comment]
@tyronx I think it is good to go.

**Comment by mymagadsl** [comment]
I think too.

**Pull request merged**
